# Generated by Django 4.2.7 on 2023-11-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_joboffer_date_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
