# Generated by Django 4.2.7 on 2023-11-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
